apiVersion: v1
kind: Namespace
metadata:
  name: payments
  labels:
    name: payments
    team: payments
    policy.sigstore.dev/include: "true"
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
