apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: db-secret
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 30s
  secretStoreRef:
    name: fake-store
    kind: SecretStore
  target:
    name: db-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
  - secretKey: password
    remoteRef:
      key: /w10/demo/db-password
      version: v1
      conversionStrategy: Default
      decodingStrategy: None
      metadataPolicy: None
