apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-reader
  namespace: demo
  labels:
    app: secret-reader
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secret-reader
  template:
    metadata:
      labels:
        app: secret-reader
    spec:
      containers:
      - name: reader
        image: busybox:1.36
        command: ["sh", "-c", "while true; do date; cat /etc/db/password; sleep 10; done"]
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
        volumeMounts:
        - name: db-secret
          mountPath: /etc/db
          readOnly: true
      volumes:
      - name: db-secret
        secret:
          secretName: db-secret
