apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: fake-store
  namespace: demo
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  provider:
    fake:
      data:
      - key: /w10/demo/db-password
        value: initial-db-password
        version: v1
